survey_labels_dict = {
    "sitecode": "Site code",
    "sitename": "Site name",
    "sitetype": "Site type",
    "sitetypenum": "1=District, 2=State, 3=National",
    "year": "4-digit Year of survey",
    "survyear": "1=1991...15=2019",
    "weight": "Analysis weight",
    "stratum": "Analysis stratum",
    "PSU": "Analysis primary sampling unit",
    "record": "Record ID",
    "age": "Age group",
    "sex": "1=Female, 2=Male",
    "grade": "1=9th...4=12th grade",
    "race4": "4-level race variable",
    "race7": "7-level race variable",
    "stheight": "Height in meters",
    "stweight": "Weight in kilograms",
    "bmi": "Body Mass Index",
    "bmipct": "BMI percentile",
    "qnobese": "Had obesity",
    "qnowt": "Were Overweight",
    "q66": "Sexual identity",
    "q65": "Sex of sexual contacts",
    "sexid": "Sexual identity",
    "sexid2": "Collapsed sexual identity",
    "sexpart": "Sex of sex contact(s)",
    "sexpart2": "Collapsed sex of sex contact(s)",
    "q8": "Seat belt use",
    "q9": "Riding with a drinking driver",
    "q10": "Drinking and driving",
    "q11": "Texting and driving",
    "q12": "Weapon carrying",
    "q13": "Weapon carrying at school",
    "q14": "Gun carrying past 12 mos",
    "q15": "Safety concerns at school",
    "q16": "Threatened at school",
    "q17": "Physical fighting",
    "q18": "Physical fighting at school",
    "q19": "Forced sexual intercourse",
    "q20": "Sexual violence",
    "q21": "Sexual dating violence",
    "q22": "Physical dating violence",
    "q23": "Bullying at school",
    "q24": "Electronic bullying",
    "q25": "Sad or hopeless",
    "q26": "Considered suicide",
    "q27": "Made a suicide plan",
    "q28": "Attempted suicide",
    "q29": "Injurious suicide attempt",
    "q30": "Ever cigarette use",
    "q31": "Initiation of cigarette smoking",
    "q32": "Current cigarette use",
    "q33": "Smoked >10 cigarettes",
    "q34": "Electronic vapor product use",
    "q35": "Current electronic vapor product use",
    "q36": "EVP from store",
    "q37": "Current smokeless tobacco use",
    "q38": "Current cigar use",
    "q39": "All tobacco product cessation",
    "q40": "Initiation of alcohol use",
    "q41": "Current alcohol use",
    "q42": "Current binge drinking",
    "q43": "Largest number of drinks",
    "q44": "Source of alcohol",
    "q45": "Ever marijuana use",
    "q46": "Initiation of marijuana use",
    "q47": "Current marijuana use",
    "q48": "Ever synthetic marijuana use",
    "q49": "Ever prescription pain medicine use",
    "q50": "Ever cocaine use",
    "q51": "Ever inhalant use",
    "q52": "Ever heroin use",
    "q53": "Ever methamphetamine use",
    "q54": "Ever ecstasy use",
    "q55": "Ever steroid use",
    "q56": "Illegal injected drug use",
    "q57": "Illegal drugs at school",
    "q58": "Ever sexual intercourse",
    "q59": "Sex before 13 years",
    "q60": "Multiple sex partners",
    "q61": "Current sexual activity",
    "q62": "Alcohol/drugs and sex",
    "q63": "Condom use",
    "q64": "Birth control pill use",
    "q67": "Perception of weight",
    "q68": "Weight loss",
    "q69": "Fruit juice drinking",
    "q70": "Fruit eating",
    "q71": "Green salad eating",
    "q72": "Potato eating",
    "q73": "Carrot eating",
    "q74": "Other vegetable eating",
    "q75": "No soda drinking",
    "q76": "No milk drinking",
    "q77": "Breakfast eating",
    "q78": "Physical activity >= 5 days",
    "q79": "Television watching",
    "q80": "Computer use",
    "q81": "PE attendance",
    "q82": "Sports team participation",
    "q83": "Concussion",
    "q84": "HIV testing",
    "q85": "STD testing",
    "q86": "Oral health care",
    "q87": "Asthma",
    "q88": "Sleep",
    "q89": "Grades in school",
    # "qn8": "Rarely or never wore a seat belt",
    # "qn9": "Rode with a driver who had been drinking alcohol",
    # "qn10": "Drove when drinking alcohol",
    # "qn11": "Texted or e-mailed while driving a car or other vehicle",
    # "qn12": "Carried a weapon",
    # "qn13": "Carried a weapon on school property",
    # "qn14": "Carried a gun",
    # "qn15": "Did not go to school because they felt unsafe at school or on their way to or from school",
    # "qn16": "Were threatened or injured with a weapon on school property",
    # "qn17": "Were in a physical fight",
    # "qn18": "Were in a physical fight on school property",
    # "qn19": "Were ever physically forced to have sexual intercourse",
    # "qn20": "Experienced sexual violence",
    # "qn21": "Experienced sexual dating violence",
    # "qn22": "Experienced physical dating violence",
    # "qn23": "Were bullied on school property",
    # "qn24": "Were electronically bullied",
    # "qn25": "Felt sad or hopeless",
    # "qn26": "Seriously considered attempting suicide",
    # "qn27": "Made a plan about how they would attempt suicide",
    # "qn28": "Attempted suicide",
    # "qn29": "Had a suicide attempt that resulted in an injury, poisoning, or overdose that had to be treated by a doctor or nurse",
    # "qn30": "Ever tried cigarette smoking",
    # "qn31": "First tried cigarette smoking before age 13 years",
    # "qn32": "Currently smoked cigarettes",
    # "qn33": "Smoked more than 10 cigarettes per day",
    # "qn34": "Ever used an electronic vapor product",
    # "qn35": "Currently used an electronic vapor product",
    # "qn36": "Usually got their own electronic vapor products by buying them in a store",
    # "qn37": "Currently used smokeless tobacco",
    # "qn38": "Currently smoked cigars",
    # "qn39": "Tried to quit using all tobacco products",
    # "qn40": "Had their first drink of alcohol before age 13 years",
    # "qn41": "Currently drank alcohol",
    # "qn42": "Currently were binge drinking",
    # "qn43": "Reported that the largest number of drinks they had in a row was 10 or more",
    # "qn44": "Usually got the alcohol they drank by someone giving it to them",
    # "qn45": "Ever used marijuana",
    # "qn46": "Tried marijuana for the first time before age 13 years",
    # "qn47": "Currently used marijuana",
    # "qn48": "Ever used synthetic marijuana",
    # "qn49": "Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it",
    # "qn50": "Ever used cocaine",
    # "qn51": "Ever used inhalants",
    # "qn52": "Ever used heroin",
    # "qn53": "Ever used methamphetamines",
    # "qn54": "Ever used ecstasy",
    # "qn55": "Ever took steroids without a doctor's prescription",
    # "qn56": "Ever injected any illegal drug",
    # "qn57": "Were offered, sold, or given an illegal drug on school property",
    # "qn58": "Ever had sexual intercourse",
    # "qn59": "Had sexual intercourse for the first time before age 13 years",
    # "qn60": "Had sexual intercourse with four or more persons during their life",
    # "qn61": "Were currently sexually active",
    # "qn62": "Drank alcohol or used drugs before last sexual intercourse",
    # "qn63": "Used a condom during last sexual intercourse",
    # "qn64": "Used birth control pills before last sexual intercourse",
    # "qn67": "Described themselves as slightly or very overweight",
    # "qn68": "Were trying to lose weight",
    # "qn69": "Did not drink fruit juice",
    # "qn70": "Did not eat fruit",
    # "qn71": "Did not eat green salad",
    # "qn72": "Did not eat potatoes",
    # "qn73": "Did not eat carrots",
    # "qn74": "Did not eat other vegetables",
    # "qn75": "Did not drink a can, bottle, or glass of soda or pop",
    # "qn76": "Did not drink milk",
    # "qn77": "Did not eat breakfast",
    # "qn78": "Were physically active at least 60 minutes per day on 5 or more days",
    # "qn79": "Watched television 3 or more hours per day",
    # "qn80": "Played video or computer games or used a computer 3 or more hours per day",
    # "qn81": "Attended physical education (PE) classes on 1 or more days",
    # "qn82": "Played on at least one sports team",
    # "qn83": "Had a concussion from playing a sport or being physically active",
    # "qn84": "Were ever tested for human immunodeficiency virus (HIV)",
    # "qn85": "Were ever testing for an STD",
    # "qn86": "Saw a dentist",
    # "qn87": "Had ever been told by a doctor or nurse that they had asthma",
    # "qn88": "Got 8 or more hours of sleep",
    # "qn89": "Described their grades in school as mostly A's or B's",
    
    # "qnfrcig": "Currently smoked cigarettes frequently",
    # "qndaycig": "Currently smoked cigarettes daily",
    # "qnfrevp": "Currently used an electronic vapor product frequently",
    # "qndayevp": "Currently used an elecctronic vapor product daily",
    # "qnfrcgr": "Currently smoked cigars frequently",
    # "qndaycgr": "Currently smoked cigars daily",
    # "qntb2": "Currently smoked cigarettes or cigars",
    # "qntb3": "Currently smoked cigarettes or cigars or used smokeless tobacco",
    # "qntb4": "Currently smoked cigarettes or cigars or used smokeless tobacco or electronic vapor products",
    # "qntb5": "Currently smoked cigarettes or used electronic vapor products",
    # "qniudimp": "Used an IUD (e.g., Mirena or ParaGard) or implant (e.g., Implanon or Nexplanon) before last sexual intercourse",
    # "qnothhpl": "Used birth control pills; an IUD (such as Mirena or ParaGard) or implant (such as Implanon or Nexplanon); or a shot (such as Depo-Provera), patch (such as OrthoEvra), or birth control ring (such as NuvaRing) before last sexual intercourse",
    # "qndualbc": "Used both a condom during last sexual intercourse and birth control pills; an IUD (such as Mirena or ParaGard) or implant (such as Implanon or Nexplanon); or a shot (such as Depo-Provera), patch (such as OrthoEvra), or birth control ring (such as NuvaRing)",
    # "qnbcnone": "Did not use any method to prevent pregnancy during last sexual intercourse",
    # "qnfr0": "Did not eat fruit or drink 100% fruit juices",
    # "qnfr1": "Ate fruit or drank 100% fruit juices one or more times per day",
    # "qnfr2": "Ate fruit or drank 100% fruit juices two or more times per day",
    # "qnveg0": "Did not eat vegetables",
    # "qnveg1": "Ate vegetables one or more times per day",
    # "qnveg2": "Ate vegetables two or more times per day",
    # "qnveg3": "Ate vegetables three or more times per day",
    # "qnsoda1": "Drank a can, bottle, or glass of soda or pop one or more times per day",
    # "qnsoda2": "Drank a can, bottle, or glass of soda or pop two or more times per day",
    # "qnmilk1": "Drank one or more glasses per day of milk",
    # "qnmilk3": "Drank three or more glasses per day of milk",
    # "qnbk7day": "Ate breakfast on all 7 days",
    # "qnpa0day": "Did not participate in at least 60 minutes of physical activity on at least 1 day",
    # "qnpa7day": "Were physically active at least 60 minutes per day on all 7 days",
    # "qndlype": "Attended physical education (PE) classes on all 5 days",
    # "qnnodnt": "Never saw a dentist",
    "qbikehelmet": "Bicycle helmet use",
    "qdrivemarijuana": "Drive when using marijuana",
    "qcelldriving": "Cell phone use while driving",
    "qpropertydamage": "Property stolen at school >= 1 time",
    "qbullyweight": "Victim of teasing b/c of physical appearance",
    "qbullygender": "Victim of gender teasing",
    "qbullygay": "Ever been teased b/c labeled GLB",
    "qchokeself": "Ever been choked/choked self on purpose",
    "qcigschool": "Currently smoke at school >=1 days",
    "qchewtobschool": "Current snuff @ school",
    "qalcoholschool": "Current drink at school",
    "qtypealcohol2": "Type of alcohol drink most often",
    "qhowmarijuana": "Usual use of marijuana",
    "qmarijuanaschool": "Marijuana use at school",
    "qcurrentopioid": "Times take pain medicine w/o prescription 30d",
    "qcurrentcocaine": "Current cocaine use",
    "qcurrentheroin": "Current heroin use",
    "qcurrentmeth": "Current meth use",
    "qhallucdrug": "Ever used hallucinogenic drugs",
    "qprescription30d": "Times take drug w/o prescription 30d",
    "qgenderexp": "Others description of your masc/fem",
    "qtaughtHIV": "Ever taught about AIDS/HIV at school",
    "qtaughtsexed": "Ever had sex education in school",
    "qtaughtstd": "Ever been taught in school about STDs",
    "qtaughtcondom": "Ever been taught in school about how to use condom",
    "qtaughtbc": "Ever been taught about BC methods in sch",
    "qdietpop": "Diet soda drinking >=1 time/day",
    "qcoffeetea": "Coffee/tea drinking >=1 time/day",
    "qsportsdrink": "Sports drinks",
    "qenergydrink": "Energy drink >=1 time/day",
    "qsugardrink": "Sugar-sweetened beverage >=1 time/day",
    "qwater": "Plain water",
    "qfastfood": "Meal/snack fast food >= 3 days",
    "qfoodallergy": "Food allergies",
    "qwenthungry": "How often went hungry",
    "qmusclestrength": "Muscle strengthening",
    "qsunscreenuse": "Sunscreen use outside",
    "qindoortanning": "Indoor tanning",
    "qsunburn": "Sunburn",
    "qconcentrating": "Difficulty concentrating",
    "qcurrentasthma": "Current asthma",
    "qwheresleep": "Homelessness",
    "qspeakenglish": "How well speak English",
    "qtransgender": "Transgender",
    # "qnbikehelmet": "Rarely or never wore a bicycle helmet",
    # "qndrivemarijuana": "Drove a car or other vehicle when they had been using marijuana",
    # "qncelldriving": "Talked on a cell phone use while driving",
    # "qnpropertydamage": "Reported that their property had been stolen or deliberately damaged on school property one or more times",
    # "qnbullyweight": "Have been the victim of teasing or name calling because of their weight, size, or physical appearance",
    # "qnbullygender": "Have been the victim of teasing or name calling because of their gender",
    # "qnbullygay": "Have been the victim of teasing or name calling because someone thought they were gay, lesbian, or bisexual",
    # "qnchokeself": "Have ever been choked by someone or tried to choke themselves on purpose",
    # "qncigschool": "Smoked cigarettes on school property",
    # "qnchewtobschool": "Used chewing tobacco, snuff, or dip on school property",
    # "qnalcoholschool": "Currently had at least one drink of alcohol on school property",
    # "qntypealcohol2": "Reported liquor as the type of alcohol they drank most often",
    # "qnhowmarijuana": "Usually used marijuana by smoking it in a joint, bong, pipe, or blunt",
    # "qnmarijuanaschool": "Used marijuana on school property",
    # "qncurrentopioid": "Currently took prescription pain medicine without a doctor's prescription",
    # "qncurrentcocaine": "Currently used any form of cocaine",
    # "qncurrentheroin": "Currently used heroin",
    # "qncurrentmeth": "Currently used methamphetamines",
    # "qnhallucdrug": "Ever used hallucinogenic drugs",
    # "qnprescription30d": "Currently took a prescription drug without a doctor's prescription",
    # "qnillict": "Ever used select illicit drugs",
    # "qngenderexp": "Think other people at school would describe them as equally feminine and masculine",
    # "qntaughtHIV": "Have been taught about AIDS or HIV infection in school",
    # "qntaughtsexed": "Have had sex education in school",
    # "qntaughtstd": "Have been taught in school about sexually transmitted diseases (STDs)",
    # "qntaughtcondom": "Have ever been taught in school about how to use a condom to prevent pregnancy or sexually transmitted diseases (STDs)",
    # "qntaughtbc": "Have been taught in school about birth control methods",
    # "qndietpop": "Drank a can, bottle, or glass of diet soda or pop",
    # "qncoffeetea": "Drank a cup, can, or bottle of coffee, coffee drinks, or any kind of tea",
    # "qnsportsdrink": "Did not drink a can, bottle, or glass of a sports drink",
    # "qnspdrk1": "Drank a can, bottle, or glass of a sports drink one or more times per day",
    # "qnspdrk2": "Drank a can, bottle, or glass of a sports drink two or more times per day",
    # "qnenergydrink": "Drank a can, bottle, or glass of an energy drink",
    # "qnsugardrink": "Drank a can, bottle, or glass of a sugar-sweetened beverage",
    # "qnwater": "Did not drink a bottle or glass of plain water",
    # "qnwater1": "Drank one or more glasses per day of plain water",
    # "qnwater2": "Drank two or more glasses per day of plain water",
    # "qnwater3": "Drank three or more glasses per day of plain water",
    # "qnfastfood": "Ate at least one meal or snack from a fast food restaurant",
    # "qnfoodallergy": "Have to avoid some foods because eating the food could cause an allergic reaction",
    # "qnwenthungry": "Most of the time or always went hungry because there was not enough food in their home",
    # "qnmusclestrength": "Did exercises to strengthen or tone their muscles on three or more days",
    # "qnsunscreenuse": "Most of the time or always wear sunscreen",
    # "qnindoortanning": "Used an indoor tanning device",
    # "qnsunburn": "Had a sunburn",
    # "qnconcentrating": "Have serious difficulty concentrating, remembering, or making decisions",
    # "qncurrentasthma": "Had been told by a doctor or nurse that they had asthma and who still have asthma",
    # "qnwheresleep": "Did not usually sleep in their parent's or guardian's home",
    # "qnspeakenglish": "Speak English well or very well",
    # "qntransgender": "Are transgender"
}